### ISSUE TITLE
Doesn't run

### ISSUE THREAD

**Issue by Ulrar** [elaye/mushu#4]
Hi,

I tried installing mushu but no luck running it : 

```
G@mushu: Map.elemAt: index out of range
CallStack (from HasCallStack):
  error, called at libraries/containers/Data/Map/Base.hs:1010:16 in containers-0.5.7.1:Data.Map.Base
```

I tried on gentoo, and to be safe I also tried on debian 9, same error.
Might  be something to do with the new ghc 8 ? Seems like your last commit was before it's release

**Comment by m0rphism** [comment]
Same for me on NixOS.

Also my output contains one further line:
```
"MPD error: Connection error (<socket: 55>: Data.ByteString.hGetLine: end of file)"
mushu: Map.elemAt: index out of range
CallStack (from HasCallStack):
  error, called at libraries/containers/Data/Map/Base.hs:1010:16 in containers-0.5.7.1:Data.Map.Base
```

**Comment by elaye** [comment]
Thanks for reporting the issue.
Is your MPD database empty ? If that's the case, that may be what's causing the issue.
I pushed a fix on develop for this case. You could try it from this branch and see if it works.
You could also try to populate your MPD database first.

**Comment by Ulrar** [comment]
I'm using mopdiy, so probably yeah, it's just searches on Spotify

**Comment by elaye** [comment]
Oh I see. I haven't used it but I guess that the Spotify extension for mopidy needs the client to have an exploration mode as well as a search mode but these are not implemented yet in mushu.
