### ISSUE TITLE
type-errors prevent building

### ISSUE THREAD

**Issue by cornservant** [elaye/mushu#5]
Mushu may be incompatible with the version of brick in stack lts-10.0.

Here's the build log: [mushu-0.1.1.log](https://github.com/elaye/mushu/files/1632240/mushu-0.1.1.log)

In particular the following type signatures don't match anymore:

- [editorText](https://github.com/jtdaugherty/brick/blob/master/src/Brick/Widgets/Edit.hs#L102) used in [app/UI/Widgets/Filter.hs](https://github.com/elaye/mushu/blob/master/app/UI/Widgets/Filter.hs#L49)
- [renderEditor](https://github.com/jtdaugherty/brick/blob/master/src/Brick/Widgets/Edit.hs#L148) used in [app/UI/Widgets/Filter.hs](https://github.com/elaye/mushu/blob/master/app/UI/Widgets/Filter.hs#L54)

**Comment by elaye** [comment]
Thanks for reporting the issue!
I've updated the resolver to lts-12.6 and fixed the compilation problems.
